FROM openjdk:11

RUN apt-get update && apt install git && apt-get install maven -y
RUN git clone https://github.com/Julia1999000/web_laba5.git -b master
RUN mvn -f web_laba5/pom.xml clean package

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "web_laba5/target/back_db_lab4_web-1.0-SNAPSHOT.jar"]